### ISSUE TITLE
1 - Datenbank planen & migrieren

### ISSUE THREAD

**Issue by AndrasTarlos** [02Gqbriel/m150-osCommerce#1]
Datenbankattribute Gewicht und Grösse hinzufügen. 

Aufwand: 1.5h
Vorgänger: -

**Comment by isufhasanii** [comment]
Planung:
Aufbau der Attribute:
product_length, decimal, (5, 2) not null
product_width, decimal, (5, 2) not null
product_height, decimal, (5, 2) not null

**Comment by 02Gqbriel** [comment]
Realisieren:
``` sql
USE webshop;

ALTER TABLE products ADD products_depth decimal(5,2) UNSIGNED NOT NULL;
ALTER TABLE products ADD products_height decimal(5,2) UNSIGNED NOT NULL;
ALTER TABLE products ADD products_width decimal(5,2) UNSIGNED NOT NULL;
```
