### ISSUE TITLE
2 - Datenbank Migration Testen

### ISSUE THREAD

**Issue by AndrasTarlos** [02Gqbriel/m150-osCommerce#3]
Die Migration testen und Testergebnisse protokolieren. 

Aufwand: 1h
Vorgänger: 1

**Comment by 02Gqbriel** [comment]
| **Testverantwortlicher**                             | Gabriel Egli                   | **Datum**                  | 14.12.2022       |
| ---------------------------------------------------- | ------------------------------ | -------------------------- | ---------------- |
|                                                      |                                |                            |                  |
| **Testbeschreibung**                                 | **Erwartetes Resultat**        | **Tatsächliches Resultat** | **Testergebnis** |
| Spalte `products_width` kann hinzugefügt werden.  | Korrekte Spalte wird ergänzt   | Spalte wurde ergänzt       | Erfolgreich      |
| Spalte `products_height` kann hinzugefügt werden. | Korrekte Spalte wird ergänzt   | Spalte wurde ergänzt       | Erfolgreich      |
| Spalte `products_depth` kann hinzugefügt werden.  | Korrekte Spalte wird ergänzt   | Spalte wurde ergänzt       | Erfolgreich      |
| Spalte `products_width` kann angezeigt werden.    | Korrekte Spalte wird angezeigt | Spalte wurde angezeigt     | Erfolgreich      |
| Spalte `products_height` kann angezeigt werden.   | Korrekte Spalte wird angezeigt | Spalte wurde angezeigt     | Erfolgreich      |
| Spalte `products_depth` kann angezeigt werden.    | Korrekte Spalte wird angezeigt | Spalte wurde angezeigt     | Erfolgreich      |

**Comment by 02Gqbriel** [comment]
Test wurden durchgeführt und waren erfolgreich.
