### ISSUE TITLE
4 - Datenbank Testwerte ergänzen 

### ISSUE THREAD

**Issue by AndrasTarlos** [02Gqbriel/m150-osCommerce#6]
Die Attribute Gewicht und Grösse für die bereits erstellten Produkte ergänzen (erfinden). 

Aufwand: 1h
Vorgänger: 1-3

**Comment by isufhasanii** [comment]
Ausführung:
UPDATE products
SET products_depth = 19.0, products_width = 13.5, products_height = 1.4
WHERE products_id = 4;

UPDATE products
SET products_depth = 'a', products_width = 13.5, products_height = 1.4
WHERE products_id = 5;

UPDATE products
SET products_depth = -19.0, products_width = 13.5, products_height = 1.4
WHERE products_id = 6;

UPDATE products
SET products_depth = 100000.4, products_width = 13.5, products_height = 1.4
WHERE products_id = 7;

UPDATE products
SET products_depth = 19.64859, products_width = 13.5, products_height = 1.4
WHERE products_id = 8;

UPDATE products
SET products_depth = 19.0, products_width = -13.5, products_height = 1.4
WHERE products_id = 9;

UPDATE products
SET products_depth = 19.0, products_width = 'a', products_height = 1.4
WHERE products_id = 10;

UPDATE products
SET products_depth = 19.0, products_width = 100003.5, products_height = 1.4
WHERE products_id = 11;

UPDATE products
SET products_depth = 19.0, products_width = 13.56775, products_height = 1.4
WHERE products_id = 12;

UPDATE products
SET products_depth = 19.0, products_width = 13.5, products_height = -1.4
WHERE products_id = 13;

UPDATE products
SET products_depth = 19.0, products_width = 13.5, products_height = 'a'
WHERE products_id = 14;

UPDATE products
SET products_depth = 19.0, products_width = 13.5, products_height = 1000000.4
WHERE products_id = 15;

UPDATE products
SET products_depth = 19.0, products_width = 13.5, products_height = 1.4747756
WHERE products_id = 16;
