### ISSUE TITLE
5 - Datenbank Testwerte prüfen/testen 

### ISSUE THREAD

**Issue by AndrasTarlos** [02Gqbriel/m150-osCommerce#7]
Die ergänzten Attribute überfliegen und auf Korrektheit testen. 

Aufwände: 1h
Vorgänger: 4

**Comment by 02Gqbriel** [comment]
| **Testverantwortlicher**                                                                                | Gabriel Egli                   | **Datum**                      | 21.12.2022       |
| ------------------------------------------------------------------------------------------------------- | ------------------------------ | ------------------------------ | ---------------- |
|                                                                                                         |                                |                                |                  |
| **Testbeschreibung**                                                                                    | **Erwartetes Resultat**        | **Tatsächliches Resultat**     | **Testergebnis** |
| Bedingung einhaltende Werte können in \`products\_width\` hinzugefügt werden.                           | Werte werden hinzugefügt       | Werte wurden hinzugefügt       | Erfolgreich      |
| Bedingung einhaltende Werte können in \`products\_height\` hinzugefügt werden.                          | Werte werden hinzugefügt       | Werte wurden hinzugefügt       | Erfolgreich      |
| Bedingung einhaltende Werte können in \`products\_depth\` hinzugefügt werden.                           | Werte werden hinzugefügt       | Werte wurden hinzugefügt       | Erfolgreich      |
| Negative Werte können **nicht** in \`products\_width\` hinzugefügt werden.                              | Werte werden nicht hinzugefügt | Werte wurden nicht hinzugefügt | Erfolgreich      |
| Negative Werte können **nicht** in \`products\_height\` hinzugefügt werden.                             | Werte werden nicht hinzugefügt | Werte wurden nicht hinzugefügt | Erfolgreich      |
| Negative Werte können **nicht** in \`products\_depth\` hinzugefügt werden.                              | Werte werden nicht hinzugefügt | Werte wurden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu gross sind, können **nicht** in \`products\_width\` hinzugefügt werden.                | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu gross sind, können **nicht** in \`products\_height\` hinzugefügt werden.               | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu gross sind, können **nicht** in \`products\_depth\` hinzugefügt werden.                | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu viele Kommastellen haben, können **nicht** in \`products\_width\` hinzugefügt werden.  | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu viele Kommastellen haben, können **nicht** in \`products\_height\` hinzugefügt werden. | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
| Werte, welche zu viele Kommastellen haben, können **nicht** in \`products\_depth\` hinzugefügt werden.  | Werte werden nicht hinzugefügt | Werte werden nicht hinzugefügt | Erfolgreich      |
